=== FrancineO/easa-dxcomponents/src/components/EASA_Extensions_SORA/drone-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Generated schema for Root",
  "type": "object",
  "properties": {
    "uas": {
      "type": "object",
      "properties": {
        "model": {
          "type": "string"
        },
        "type": {
          "type": "string"
        },
        "weigth": {
          "type": "number"
        },
        "maxSpeed": {
          "type": "number"
        },
        "heightOfFlightGeography": {
          "type": "number"
        },
        "maxAutonomy": {
          "type": "number"
        },
        "characteristicDimension": {
          "type": "number"
        }
      },
      "required": [
        "model",
        "type",
        "weigth",
        "maxSpeed",
        "heightOfFlightGeography",
        "maxAutonomy",
        "characteristicDimension"
      ]
    },
    "altimetry": {
      "type": "number"
    },
    "operationType": {
      "type": "string",
      "enum": ["BVLOS", "VLOS", "EVLOS"]
    },
    "maxWindSpeeed": {
      "type": "number"
    },
    "maxPitch": {
      "type": "number"
    },
    "maxSail": {
      "type": "number"
    },
    "containment": {
      "type": "string",
      "enum": ["low", "medium", "high"]
    }
  },
  "required": ["uas", "altimetry", "operationType", "maxWindSpeeed", "maxPitch"]
}

=== FrancineO/easa-dxcomponents/src/components/EASA_Extensions_SORA/sample-drone.json
{
  "uas": {
    "model": "my-model",
    "type": "my-type",
    "weigth": 1,
    "maxSpeed": 15,
    "heightOfFlightGeography": 20,
    "maxAutonomy": 30,
    "characteristicDimension": 45
  },
  "altimetry": 100,
  "operationType": "BVLOS",
  "maxWindSpeeed": 20,
  "maxPitch": 40,
  "maxSail": 1,
  "containment": "low"
}
